# Generated by Django 4.0.4 on 2022-05-10 12:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule_students', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='name',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator('[А-ЯЕа-яё]+\\s[А-ЯЕа-яё]{1}\\.\\s*[А-ЯЕа-яё]{1}\\.')], verbose_name='Студент'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='teacher',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator('[А-ЯЕа-яё]+\\s[А-ЯЕа-яё]{1}\\.\\s*[А-ЯЕа-яё]{1}\\.')], verbose_name='Преподаватель'),
        ),
    ]
